# Machine Learning
Author: Scottie Housholder  
Course: MAT 311  
Updated: November 17, 2025#TODO:

In [801]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [802]:
def find_k(size):
    """
    Return the number of neighbors a KNN algorithm should have
    Returns the square root of the given number and makes sure it's odd
    """

    k = round(size**0.5)
    if k % 2 == 0:
        return k-1
    return k

In [803]:
test_data = pd.read_csv("../data/processed/test_cleaned_temp.csv", index_col=0)
train_data = pd.read_csv("../data/processed/train_cleaned_temp.csv", index_col=0)

#TODO: Change n_neighbors to sqrt(len(dataset))
knn = KNeighborsClassifier(find_k(len(test_data)))
# forest = RandomForestClassifier()

In [804]:
print(train_data.corrwith(train_data["Churn"]).sort_values())

Total Spend                  -0.372350
Contract Length_Quarterly    -0.141252
Contract Length_Annual       -0.138528
Usage Frequency              -0.049018
Tenure                       -0.016920
Subscription Type_Premium    -0.010027
Subscription Type_Standard   -0.006670
CustomerID                    0.001484
Subscription Type_Basic       0.016940
Last Interaction              0.100025
Gender_Female                 0.158337
Age                           0.189481
Payment Delay                 0.329147
Contract Length_Monthly       0.401125
Support Calls                 0.424620
Churn                         1.000000
Customer Status_inactive      1.000000
dtype: float64

In [805]:
train_data.columns

Index(['CustomerID', 'Age', 'Tenure', 'Usage Frequency', 'Support Calls',
       'Payment Delay', 'Total Spend', 'Last Interaction', 'Churn',
       'Gender_Female', 'Subscription Type_Basic', 'Subscription Type_Premium',
       'Subscription Type_Standard', 'Contract Length_Annual',
       'Contract Length_Monthly', 'Contract Length_Quarterly',
       'Customer Status_inactive'],
      dtype='object')

In [806]:
X_train = train_data[['Support Calls', "Contract Length_Monthly", "Payment Delay", "Age"]]
X_test = test_data[['Support Calls', "Contract Length_Monthly", "Payment Delay", "Age"]]
y_train = train_data["Churn"]
train_data.isna().sum()

CustomerID                    0
Age                           0
Tenure                        0
Usage Frequency               0
Support Calls                 0
Payment Delay                 0
Total Spend                   0
Last Interaction              0
Churn                         0
Gender_Female                 0
Subscription Type_Basic       0
Subscription Type_Premium     0
Subscription Type_Standard    0
Contract Length_Annual        0
Contract Length_Monthly       0
Contract Length_Quarterly     0
Customer Status_inactive      0
dtype: int64

In [807]:
knn_fit = knn.fit(X_train, y_train)
# forest_fit = forest.fit(X_train, y_train)

# cols = X_train.columns

# knn_fit

In [808]:
test_data.columns

Index(['CustomerID', 'Age', 'Tenure', 'Usage Frequency', 'Support Calls',
       'Payment Delay', 'Total Spend', 'Last Interaction', 'Gender_Female',
       'Subscription Type_Basic', 'Subscription Type_Premium',
       'Subscription Type_Standard', 'Contract Length_Annual',
       'Contract Length_Monthly', 'Contract Length_Quarterly'],
      dtype='object')

In [809]:
prob_predict = pd.DataFrame(knn_fit.predict_proba(X_test))
# prob_predict = pd.DataFrame(forest_fit.predict_proba(X_test))
prob_predict["CustomerID"] = test_data["CustomerID"]
prob_predict = prob_predict.set_index("CustomerID")
prob_predict

                   0         1
CustomerID
262106      0.271233  0.728767
37061       0.635616  0.364384
361832      0.978082  0.021918
425516      0.208219  0.791781
60597       0.328767  0.671233
...              ...       ...
396573      0.356164  0.643836
452602      0.213699  0.786301
424958      0.065753  0.934247
242104      0.397260  0.602740
132430      0.909589  0.090411

[133776 rows x 2 columns]

In [810]:
prob_predict = prob_predict.rename(columns={1:"Churn"})
prob_predict = prob_predict.drop(0, axis=1)
print(prob_predict)

               Churn
CustomerID
262106      0.728767
37061       0.364384
361832      0.021918
425516      0.791781
60597       0.671233
...              ...
396573      0.643836
452602      0.786301
424958      0.934247
242104      0.602740
132430      0.090411

[133776 rows x 1 columns]

In [811]:
print(prob_predict["Churn"].unique())
print(prob_predict["Churn"].nunique())

[0.72876712 0.36438356 0.02191781 0.79178082 0.67123288 0.0630137
 0.02739726 0.87671233 0.91232877 0.81369863 0.80821918 0.65479452
 0.92876712 0.6630137  0.91506849 0.89589041 0.81643836 0.03561644
 0.58082192 0.63287671 0.78630137 0.86575342 0.88219178 0.65753425
 0.70410959 0.75068493 0.74794521 0.06027397 0.67945205 0.88767123
 0.76438356 0.66575342 0.66849315 0.76164384 0.15616438 0.8109589
 0.64109589 0.73972603 0.61917808 0.71232877 0.11232877 0.04657534
 0.68493151 0.63013699 0.89041096 0.88493151 0.21917808 0.05205479
 0.64657534 0.89315068 0.90410959 0.61369863 0.62191781 0.87945205
 0.72328767 0.22465753 0.84383562 0.90684932 0.03287671 0.76712329
 0.69041096 0.71780822 0.82739726 0.72054795 0.09041096 0.27123288
 0.83013699 0.04383562 0.5369863  0.63835616 0.66027397 0.86849315
 0.79452055 0.82191781 0.75342466 0.25479452 0.90958904 0.67671233
 0.71506849 0.84931507 0.70958904 0.05753425 0.93150685 0.78356164
 0.86027397 0.68219178 0.89863014 0.07123288 0.73424658 0.8739726
 0.95616438 0.69315068 0.03835616 0.43835616 0.69589041 0.40273973
 0.60273973 0.62739726 0.74520548 0.6        0.75890411 0.63561644
 0.79726027 0.83561644 0.64931507 0.2630137  0.0739726  0.70684932
 0.44931507 0.07945205 0.84657534 0.09315068 0.7890411  0.4
 0.77808219 0.92054795 0.2        0.74246575 0.68767123 0.81917808
 0.90136986 0.70136986 0.77534247 0.69863014 0.04109589 0.08767123
 0.06849315 0.01917808 0.23835616 0.93972603 0.62465753 0.8630137
 0.85753425 0.45479452 0.7369863  0.8        0.07671233 0.65205479
 0.9260274  0.87123288 0.49041096 0.31780822 0.6739726  0.50410959
 0.82465753 0.53424658 0.04931507 0.7260274  0.55616438 0.77260274
 0.06575342 0.03013699 0.61643836 0.83287671 0.05479452 0.56438356
 0.16986301 0.80273973 0.18082192 0.08219178 0.22191781 0.94520548
 0.85479452 0.45753425 0.41917808 0.47945205 0.75616438 0.92328767
 0.55068493 0.97534247 0.09589041 0.08493151 0.9369863  0.17260274
 0.95342466 0.02465753 0.39726027 0.53972603 0.80547945 0.83835616
 0.09863014 0.28493151 0.85205479 0.14246575 0.11780822 0.64383562
 0.59452055 0.23287671 0.34794521 0.95890411 0.38082192 0.4630137
 0.28767123 0.01643836 0.10410959 0.93424658 0.52328767 0.19452055
 0.94794521 0.24931507 0.10136986 0.76986301 0.78082192 0.18356164
 0.40547945 0.49315068 0.91780822 0.1260274  0.44109589 0.73150685
 0.10684932 0.32328767 0.13424658 0.43561644 0.24383562 0.94246575
 0.21369863 0.84109589 0.37260274 0.32876712 0.51506849 0.01369863
 0.2109589  0.2739726  0.44657534 0.42739726 0.41643836 0.96438356
 0.23561644 0.54794521 0.55890411 0.57260274 0.39178082 0.60547945
 0.13150685 0.50958904 0.12328767 0.37534247 0.10958904 0.33972603
 0.12054795 0.36712329 0.54246575 0.43013699 0.49589041 0.38356164
 0.26575342 0.52876712 0.26027397 0.24657534 0.16438356 0.11506849
 0.24109589 0.3890411  0.4739726  0.6109589  0.20547945 0.35342466
 0.15342466 0.42465753 0.58356164 0.1369863  0.95068493 0.37808219
 0.33424658 0.27671233 0.35616438 0.44383562 0.19178082 0.17534247
 0.38630137 0.32054795 0.29589041 0.40821918 0.57534247 0.26849315
 0.39452055 0.47123288 0.23013699 0.13972603 0.97260274 0.3260274
 0.96712329 0.35068493 0.20821918 0.58630137 0.96164384 0.41369863
 0.30410959 0.55342466 0.49863014 0.22739726 0.46575342 0.12876712
 0.42191781 0.29863014 0.25753425 0.54520548 0.36164384 0.31506849
 0.20273973 0.56164384 0.16164384 0.43287671 0.00821918 0.5890411
 0.34246575 0.36986301 0.25205479 0.48493151 0.30958904 0.60821918
 0.15890411 0.29315068 0.59726027 0.27945205 0.51780822 0.5260274
 0.17808219 0.16712329 0.96986301 0.34520548 0.46849315 0.52054795
 0.53150685 0.19726027 0.59178082 0.28219178 0.21643836 0.33150685
 0.48219178 0.57808219 0.48767123 0.56986301 0.29041096 0.51232877
 0.30684932 0.46027397 0.31232877 0.3369863  0.56712329 0.4109589
 0.50136986 0.18630137 0.50684932 0.35890411 0.0109589  0.47671233
 0.14794521 0.14520548 0.15068493 0.1890411  0.30136986 0.97808219
 0.45205479]
355

In [812]:
prob_predict.head()

               Churn
CustomerID
262106      0.728767
37061       0.364384
361832      0.021918
425516      0.791781
60597       0.671233

In [813]:
prob_predict.index.isna()

array([False, False, False, ..., False, False, False])

In [814]:
prob_predict.to_csv("../submission.csv")

In [815]:
# sns.barplot(x=cols, y=forest_fit.feature_importances_)
# plt.xticks(rotation=90)
# plt.show()